### ISSUE TITLE
Boolean attribute changes not set to property

### ISSUE THREAD

**Issue by SPrinss** [woutervroege/html-element-mixins#11]
```
  attributeChangedCallback(attrName, oldValue, newValue) {
    if(oldValue === newValue) return;
    const propertyName = this.constructor.__getPropertyNameByAttributeName.call(this, attrName);
    if(!propertyName) return;
    if(!newValue && !this[propertyName]) return;
    this.constructor.__setPropertyWithAttributeValue.call(this, propertyName, newValue);
  }
```
In `property-reflector-mixin.js ` the method `attributeChangedCallback` checks for `(!newValue)`. 
Since Boolean Attributes values are set with an empty String (e.g. ''), and `!''` is false, `__setPropertyWithAttributeValue` is never called with the changed attribute (unless `!this[propertyName]` is false of course, but that's unrelated).

Consider adding something like:
`(typeof newValue === 'undefined' || newValue === null)`

Additionally, when the `''` newValue is used in `__setPropertyWithAttributeValue`, it results in the property being set by to `null` since
- `JSON.parse('')` throws an error
- the catch statement sets the property to `newValue || null`

Consider adding something like:
`if(typeof newValue === 'string' && newValue.length === 0) return this[propertyName] = true;`

**Note that String properties want to be set to '', not to true.**

**Comment by woutervroege** [comment]
Fixed bec2f58
