### ISSUE TITLE
Property change observer misses Array/Object equality

### ISSUE THREAD

**Issue by SPrinss** [woutervroege/html-element-mixins#13]
In `property-observer-mixin` `__callPropertySetter` and `initProperty`:
```
if(oldVal === this[propName]) return;
```
But:
`[] !== []`

So, the script causes an endless loop of observing -> setting -> observing.

See for example:
1. https://github.com/SPrinss/metal-elements/tree/button-group-endless-loop
2. `demo/metal-button-group.html` 
3. set options to `[{label: 'Some label', value: 1}, {label: 'Some other label', value: 2}]`
4. see console.log

**Comment by woutervroege** [comment]
@SPrinss I cannot reproduce this issue. E.g. assigning the array above to the 'friends' array in `demo/index.html` seems to work fine. Could you share an example with me?

**Comment by SPrinss** [comment]
Can't reproduce myself. :)
