### ISSUE TITLE
attributes are set in the constructor

### ISSUE THREAD

**Issue by SPrinss** [woutervroege/html-element-mixins#16]
According to the [html standard](https://html.spec.whatwg.org/multipage/custom-elements.html#custom-element-conformance):

> ### Requirements for custom element constructors and reactions :
>The element must not gain any attributes or children, as this violates the expectations of consumers who use the createElement or createElementNS methods.

See:
`oberserver-mixin.js -> constructor -> initProperties -> propertyChangedCallback -> __setAttributeWithPropertyValue`, attributes are set from constructor.

**Comment by woutervroege** [comment]
Fixed 6e6e52f2b6887389478062bb1db8afef032fd9c9
