### ISSUE TITLE
property-reflector -> this.propertyChangedCallback not a function

### ISSUE THREAD

**Issue by SPrinss** [woutervroege/html-element-mixins#4]
If I open property-reflector.html demo, I see a console.log:

`property-reflector-mixin.js:12 
Uncaught (in promise) TypeError: (intermediate value).propertyChangedCallback is not a function
`

_Adding `super.propertyChangedCallback &&` to that line resolves the error_

**Comment by woutervroege** [comment]
Fixed with 51a349fa84cfca3963fa326fa4ac50c3dfcf9b35
