### ISSUE TITLE
property-reflector: setAttribute 'some-string' throws an Error

### ISSUE THREAD

**Issue by SPrinss** [woutervroege/html-element-mixins#6]
Setting normal String properties results in 
`Uncaught SyntaxError: Unexpected token s in JSON at position 0
    at JSON.parse (<anonymous>)`

Open property-reflector.html demo 
On `customElements.whenDefined` add: ` demo.setAttribute('first-name', "Sam")`

Or, in dev-tools, change attribute` first-name=""john""` to `first-name="Sam"`

I would expect that I can set a normal String as attribute value and that `$0.getAttribute('first-name')` would result in `"john"` and not `""john""`

**Comment by woutervroege** [comment]
Fixed 7178f85b04faabef78f1e92791b17de2f0ed7f2c
